#spring.application.name=app
#spring.thymeleaf.check-template-location=false


spring.datasource.url=jdbc:mysql://localhost:3306/taskdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anamdev051p@gmail
spring.mail.password=evse wxvg zkss lxhg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true













